### PR TITLE
Lets user use number keys to set ranking 

### PR DESCRIPTION
**Pull request by EllangoK**
As above, to quickly set ranking of images the user can now just hit a number key. 0 sets it to none.

A keydown listener is created to capture input and update the html elements accordingly. To locate some of the html as well I needed to add some ids. 

Also I did some cleanup of the other key listener as well. All the logic is the exact same but previously it throws a bunch a console errors because most of the time it is null as we try to grab those elements even if we aren't on the Image Browser page, which causes undefined and null errors.

## Demo

ranking-keypress

### CODE REVIEW

**Comment by EllangoK** [comment]
also two things, one I strongly think that most the id names are very bad and we should rewrite them all so they make more sense. I will do if necessary, but I mean its not like its a lot of work.

And two, I was thinking and probably will do soon is bind delete key to the button as well.

**Comment by AlUlkesh** [comment]
Something went wrong with the merge conflict. Fixed here: https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/c1a4590d545bf68035c8e6a2f43cec04f380f2f8

**Comment by AlUlkesh** [comment]
@EllangoK Thanks. Very nice.

> most the id names are very bad

Yes.. at one point I had to make a cheat sheet, to see what's what... I'll look into it tomorrow.

**Comment by EllangoK** [comment]
> Something went wrong with the merge conflict. Fixed here: [c1a4590](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/c1a4590d545bf68035c8e6a2f43cec04f380f2f8)

ah yes accidentally missed a line somehow? in my git commit, but yeah that commit you added was the same so thanks.

> Yes.. at one point I had to make a cheat sheet, to see what's what... I'll look into it tomorrow.

ofc take your time, lmk if you need any help as well.

**Pull request merged**
