### PR TITLE
feat: update ui style

### PR DESCRIPTION
**Pull request by fennghuang**
image
update ui style

### CODE REVIEW

**Comment by AlUlkesh** [comment]
Thanks!

However when pathnames start getting longer, they get cut off fairly soon now, without an option to see their full name:

image

**Comment by fennghuang** [comment]
it can be fixed with css. 
```
#tab_image_browser .gradio-dropdown ul.options li.item {
  white-space: wrap;
  word-break: break-all
}
```
image

Fixed all drowpdown components

**Comment by AlUlkesh** [comment]
Ah, that's great with the css. Thanks.

Your latest commit in addition to the css change, has a few more changes - and now I'm not sure what your intention is.

In your first commit you put the two textfields and the button for Copy/Move in one line, making it more compact.

In the current commit they're on separate lines again and the Controlnet number now also has its own line. So making it more "un-compact".

What was your intention with these latest changes?

image

**Comment by fennghuang** [comment]
image
image

About the Directory path and Saved directories components, they should show more string length. So I changed the commit, and make it look like the border line was removed compared to the original.


And about the ControlNet Number, just want to make it look neater. The first two items are buttons, but the ControlNet Number is dropdown component.

Maybe for the "compact", should I  revert it?

**Comment by AlUlkesh** [comment]
> Maybe for the "compact", should I revert the ControlNet Number changes?

No. it's fine 😄 Thanks for explaining the thought behind the changes.

**Pull request merged**
