### PR TITLE
Added Setting to set gallery height to auto #40

### PR DESCRIPTION
**Pull request by neo-js**
Added a minimum height in css to accommodate a small gallery set #40

### CODE REVIEW

**Comment by neo-js** [comment]
Did you completely refresh your browser? (Shift+Refresh or Disable Cache)  I believe that Gradio uses some cached js that gets compiled and doesn't always reload if you don't force the refresh.  It definitely doesn't work with just a ReloadUI.

**Comment by AlUlkesh** [comment]
Yes. I also tried it on a fresh install.

**Comment by AlUlkesh** [comment]
No, cleared cache, restarted browse, still that issue.

**Comment by neo-js** [comment]
Yeah, it's happening now to me as well.  Very inconsistent.  I'll keep working at it and see if I can find what is going wrong.

**Comment by neo-js** [comment]
Seems to work fine if the gallery page isn't full, like on the last page.

**Comment by neo-js** [comment]
So, I just merged the resent changes into this fork and then updated and I'm not getting the issue of nothing showing in initial tests.  @AlUlkesh do you mind confirming if they are still an issue for you?  I did change the settings for less columns and more rows to increase the size of the previews, incase that proves to be a factor.

**Comment by AlUlkesh** [comment]
@neo-js 
Yes, unfortunately the issue persists also with this latest commit. What a frustrating issue.

**Comment by anbuzz** [comment]
f8449e137c0468ff23ddaef5e6ac6e3

image

1.Find elements similar to grid-wrap svelte-1tkea93 fixed-height
2.See index.5c217706.css file and min-height: 450px;
3.Find ".fixed-height.svelte-1tkea93.svelte-1tkea93{min-height:450px}" 
4.Modify to ".fixed-height.svelte-1tkea93.svelte-1tkea93{min-height:100vh}" 

PS:Of course, you can also modify it to a higher height, but this will lose the click to zoom function

**Comment by AlUlkesh** [comment]
There was a fix on the Gradio side. More info here:
https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/issues/40#issuecomment-1659062399

**Pull request closed without merging**
